### ISSUE TITLE
Виталий, я ничего не понимаю

### ISSUE THREAD

**Issue by Yanina-cjvnjde** [cjvnjde/psycho-tests#1]
думаю тут не нужно описание, но я напишу, чтобы посмотреть что будет. и даже прикреплю файл, раз есть такая возможность.
![Безымянный](https://user-images.githubusercontent.com/82381542/114388668-adeb1400-9b9c-11eb-9dc8-88742faa4851.png)

**Comment by cjvnjde** [comment]
![image](https://user-images.githubusercontent.com/68147661/114388796-decb4900-9b9c-11eb-96e5-9c80f90c7430.png)
@Yanina-cjvnjde

**Comment by Yanina-cjvnjde** [comment]
![hqdefault](https://user-images.githubusercontent.com/82381542/114389188-5dc08180-9b9d-11eb-8607-1ea1a4fc8167.jpg)
